### ISSUE TITLE
Use `Buffer.from()` instead of `new Buffer()`

### ISSUE THREAD

**Issue by kevva** [kevva/to-ico#10]
When targeting Node.js >=6, use Buffer.from() since new Buffer() is deprecated.

**Comment by vladgurovich** [comment]
What is the targeting in question? This commit broke our application that uses https://github.com/jantimon/favicons-webpack-plugin which in turn is dependent on https://github.com/haydenbleasel/favicons which is in turn is dependent on to-ico.
We use node v4.xx and Buffer.alloc was introduced in v5.10

**Comment by SamVerschueren** [comment]
It was backported to v4 as well, per the [docs](https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html).

**Comment by andreigabreanu** [comment]
Just wanted to say that this broke our application also (and still is). For the moment we had to revert to version 1.1.2 to keep it working . Same source problem as @vladgurovich - favicons-webpack-plugin .
