### ISSUE TITLE
Buffer.alloc compatibility

### ISSUE THREAD

**Issue by kylekatarnls** [kevva/to-ico#15]
Hi,

I just downloaded to-ico but the last version included Buffer.alloc that is not compatible with the node version 4 you're supposed to support according to your package.json.

Please consider revert this modification to keep backward compatibility (pull request #14).

Thanks,

**Comment by SamVerschueren** [comment]
`Buffer.alloc` was backported to v4.

https://nodejs.org/dist/latest-v4.x/docs/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding

**Comment by kylekatarnls** [comment]
Our project is locked in 4.4.5 right now and so I get `Buffer.alloc is undefined`

**Comment by kylekatarnls** [comment]
Hi, for quick fix, this can be done before requiring to-ico:

```js
Buffer.alloc || (Buffer.alloc = function (size, fill, encoding) {
	return new Buffer(size, fill, encoding);
})
```

But even if you don't plan to fix 4.0 to 4.4 compatibility, maybe you should update package.json to match requirements. And so if backward compability break, it should not be a patch number version increment, it should be new major version according to semver.org or at least minor.

**Comment by kylekatarnls** [comment]
Hi, do you consider the question?

**Comment by kevva** [comment]
Fixed in https://github.com/kevva/to-ico/commit/8318a24346d9e4f650665810b60d965c5fada5a5.
