### ISSUE TITLE
File generated with "resize: true" seems malformed

### ISSUE THREAD

**Issue by jraoult** [kevva/to-ico#8]
I tried to use the resize option with a single png source file and I noticed that Chrome (at least) can't read the resulting file. I also noticed that https://realfavicongenerator.net/ says that my `favicon.ico` is "ill-formed". I then used https://www.icoconverter.com/ to compare and `.ico` generated there work. That said, Preview (on my Mac) can read it properly.

**Comment by kevva** [comment]
Could you provide the original image?

**Comment by jraoult** [comment]
Any image would do but here is an example
![gh_example](https://cloud.githubusercontent.com/assets/2046871/18640168/e484f3f8-7e8e-11e6-94d3-73ab7b6cc316.png)

**Comment by jraoult** [comment]
Interestingly enough I had more luck with https://www.npmjs.com/package/png-to-ico

**Comment by kevva** [comment]
I think it has to do in which order the sizes are created. The biggest one needs to be first.

**Comment by kevva** [comment]
@jraoult, could you try installing from `master` and see if it works? It rendered fine in Chrome for me.

**Comment by jraoult** [comment]
@kevva fix verified it in Chrome. Cool.

Now, my actual goal was to fix https://www.npmjs.com/package/favicons.  So if I understand your fix properly it is a matter of ordering the given `files` by width here https://github.com/evilebottnawi/favicons/blob/d5d997f43bd4a50f7cbe511b644fabee4949e837/index.js#L46, right?

**Comment by kevva** [comment]
@jraoult, yup, that should do it. I'll probably add the sorting in here later on too.

**Comment by jraoult** [comment]
I've checked further and I feel there is something more than the order of the bitmaps going on. I can't quite yet figure it out but I've generated a `.ico` on https://realfavicongenerator.net/ that works and the same with `to-ico` and the second one doesn't work.

**Comment by jraoult** [comment]
Hmm, I think I found it: https://github.com/kevva/to-ico/blob/master/index.js#L27. You probably wanted to write (following that: http://www.blitzbasic.com/Community/post.php?topic=75770&post=847533):
```js
data.width === 256 ? 0 : data.width;
```
instead of 
```js
data.width <= 256 ? 0 : data.width;
```
Am I right?

**Comment by kevva** [comment]
@jraoult, could you try it?

**Comment by jraoult** [comment]
@kevva I did and it seems that the ordering was no the problem actually but these erroneous width and height info were. Do you want a PR?

**Comment by kevva** [comment]
@jraoult, yup, you're right. Sorry, I've already pushed out a fix, but thanks a lot for investigating and coming up with a fix!

![](http://67.media.tumblr.com/d3e6bb18630e4d9323d660d5bec2747b/tumblr_mkovbjT6Qs1qc174to1_500.gif)

**Comment by jraoult** [comment]
Glad it helped :) I'll create a PR to https://github.com/haydenbleasel/favicons to require the `1.1.2`
